services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
    depends_on:
      - pgdatabase

  ingestion:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      pgdatabase:
        condition: service_started
    command: >
      python3 ingestion.py --user root --password root --host pgdatabase --port 5432 --db ny_taxi --table-name yellow_taxi_data --url https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet

# docker run -it `
#   -e POSTGRES_USER="root" `
#   -e POSTGRES_PASSWORD="root" `
#   -e POSTGRES_DB="ny_taxi" `
#   -v c:/Users/rpatr/Desktop/DataTalksClub/homeworks/homework1/ny_taxi_postgres_data:/var/lib/postgresql/data `
#   -p 5432:5432 `
#   --network=pg-network `
#   postgres:13

# docker run -it `
#   -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" `
#   -e PGADMIN_DEFAULT_PASSWORD="root" `
#   -p 8080:80 `
#   --network=pg-network `
#   dpage/pgadmin4

# python ingestion.py `
# --user=root `
# --pass=root `
# --host=localhost `
# --port=5432 `
# --db=ny_taxi `
# --table-name=yellow_taxi_data `
# --url=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet


# docker run -it `
#   --network=pg-network `
#   ingestion-pipeline:v001 `
#   --user=root `
#   --pass=root `
#   --host=e95601d46225 `
#   --port=5432 `
#   --db=ny_taxi `
#   --table-name=yellow_taxi_data `
#   --url=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet
